name: mahallamarket
description: A hyperlocal marketplace app inspired by Karrot
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase core
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3

  # Geo & location
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  geoflutterfire2: ^2.4.1

  # UI/UX helpers
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1

  # Notifications (local)
  flutter_local_notifications: ^17.2.1

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
