name: mahallamarket
description: Hyperlocal marketplace (advanced pack)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  geoflutterfire_plus: ^0.0.32
  uuid: ^4.5.1
  rxdart: ^0.28.0
  flutter_local_notifications: ^17.2.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
