// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    return web; // Default to web for now
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkVYjVHCIzx0ShV3dTlSgv9zqheJfAODg',
    appId: '1:781280107860:web:8c263356aa8e188b22fcc1',
    messagingSenderId: '781280107860',
    projectId: 'mahallamarket-61195',
    authDomain: 'mahallamarket-61195.firebaseapp.com',
    storageBucket: 'mahallamarket-61195.firebasestorage.app',
    measurementId: 'G-CC6WMSDDEQ',
  );

}